[package]
name = "rawr"
version = "0.1.0"
authors = ["Beinsezii <beinsezii@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
copypasta = "0.7"
copypasta-ext = "0.3"
rand = "0.8"
